[package]
name = "fwos-fwd-setup"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Host program oneshot: create empty fwd and mgmt netns"

[dependencies]
libc = "0.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"
rustls = { version = "0.23", default-features = false, features = ["std", "ring", "tls12"] }
rustls-pemfile = "2"
rcgen = { version = "0.13", default-features = false, features = ["ring", "pem"] }

[[bin]]
name = "fwos-fwd-setup"
path = "src/main.rs"

[[bin]]
name = "netd"
path = "src/netd.rs"

[[bin]]
name = "fwos"
path = "src/cli.rs"

[[bin]]
name = "fwos-ui"
path = "src/ui.rs"
